#!/bin/bash

#Register the Hospital organisation in SL, along with its admin
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"org_name": "hospital", "username": "hospital_admin","password": "hosadm"}' \
	https://localhost:6023/v1/signup/admin | jq -r "."
	
#TODO
#The address of the Algorand account generated by the above API call MUST BE FUNDED at https://bank.testnet.algorand.network/

#Admin login
ADMIN_TOKEN=$(curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"username": "hospital_admin","password": "hosadm"}' \
	https://localhost:6023/v1/login | jq -r ".sl_token")

#Create a TAXII apiroot for the Hospital
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	--data '{"title": "The Hospital","description": "Hospital Group"}' \
	https://localhost:6023/hospital | jq -r "."

#Create a TAXII collection inside the Hospital's apiroot
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	--data '{"title": "Attacks","alias": "attack"}' \
	https://localhost:6023/hospital/collections | jq -r "."
	
#Store a STIX object inside the Hospital's collection "attack" -- Repeat 2 or more times
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	--data @stix-obj-example.json \
	https://localhost:6023/hospital/collections/attack/objects | jq -r "."

#Store a STIX object inside the Hospital's collection "attack" -- Repeat 2 or more times
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	--data @stix-obj-multiple.json \
	https://localhost:6023/hospital/collections/attack/objects | jq -r "."
	
########## GET FILTERED STIX OBJECTS ##########

curl -skg --request GET \
	--header "Accept: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	'https://localhost:6023/hospital/collections/attack/objects?added_after=2023/01/01&limit=2' | jq -r "."
	
curl -skg --request GET \
	--header "Accept: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	'https://localhost:6023/hospital/collections/attack/manifest?added_after=2023/01/01&limit=3&match[type]=malware&match[version]=first&match[version]=last' | jq -r "."	

curl -skg --request GET \
	--header "Accept: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	'https://localhost:6023/hospital/collections/attack/objects/bundle--2a25c3c8-5d88-4ae9-862a-cc3396442317?match[version]=last' | jq -r "."
	

curl -skg --request GET \
	--header "Accept: application/json" \
	--header "Authorization: Bearer ${ADMIN_TOKEN}" \
	'https://localhost:6023/hospital/collections/attack/objects/bundle--2a25c3c8-5d88-4ae9-862a-cc3396442317/versions?limit=1' | jq -r "."
