#!/bin/bash

#Create an API-Root for the Hospital
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"title": "The Hospital","description": "Hospital Group","slug": "hospital"}' \
	https://localhost:6012/v1/taxii/apiRoot | jq -r "."
	
#TODO
#The address of the Algorand account generated by the above API call MUST BE FUNDED at https://bank.testnet.algorand.network/
	
#Create a user for the Hospital
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"username": "hospital_user1","password": "password","groupName": "hospital"}' \
	https://localhost:6012/v1/user | jq -r "."
	
#Login with the user credentials
AUTH_TOKEN=$(curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"username": "hospital_user1","password": "password"}' \
	https://localhost:6012/v1/login)
	
#Create a collection inside the Hospital's API-Root
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--data '{"title": "Attacks","alias": "attack"}' \
	https://localhost:6012/v1/taxii/hospital/collection | jq -r "."
	
#Get collections of Hospital
curl -sk --request GET \
	--header "Accept: application/json" \
	--header "Authorization: Bearer ${AUTH_TOKEN}" \
	https://localhost:6011/hospital/collections | jq -r "."
	
#Store a STIX object inside the Hospital's collection created previously
curl -sk --request POST \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer ${AUTH_TOKEN}" \
	--data @stix-obj-example.json \
	https://localhost:6011/hospital/collections/attack/objects | jq -r "."
