#!/bin/bash

#Get the Root Token from logs of HashiCorp Vault container
#VAULT_TOKEN=$1
#VAULT_TOKEN=$(docker logs hashicorp-vault 2>&1 | grep "Root Token" | cut -d ':' -f 2)
VAULT_TOKEN=$( cat .env | grep "HCV_ROOT_TOKEN" | cut -d '=' -f 2 | tr -d \")

#Enable Key-Value (KV) secret engine
curl -s --header "X-Vault-Token: $VAULT_TOKEN"\
	--request POST \
	--data '{"type": "kv", "description": "key/value secret storage", "options": {"version": "2"}}' \
	localhost:8223/v1/sys/mounts/secret

#Create a ACL policy named "sl"
curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
	--request POST \
	--data @configs/policies/sl.json \
	localhost:8223/v1/sys/policy/sl
	
#Create a ACL policy named "sl-admins"
#--header "X-Vault-Namespace: admin"
curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
	--request POST \
	--data @configs/policies/sl-admins.json \
	localhost:8223/v1/sys/policy/sl-admins
	
#Create a ACL policy named "sl-users"
curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
	--request POST \
	--data @configs/policies/sl-users.json \
	localhost:8223/v1/sys/policy/sl-users

#Enable "userpass" authentication method	
curl -s --header "X-Vault-Token: $VAULT_TOKEN"\
	--request POST \
	--data '{"type": "userpass"}' \
	localhost:8223/v1/sys/auth/userpass

#Enable "approle" authentication method
curl -s --header "X-Vault-Token: $VAULT_TOKEN"\
	--request POST \
	--data '{"type": "approle"}' \
	localhost:8223/v1/sys/auth/approle

#Create a role named "sl" with the policy "sl" attached
curl -s --header "X-Vault-Token: $VAULT_TOKEN"\
	--request POST \
	--data '{"policies": "sl", "token_policies": "sl"}' \
	localhost:8223/v1/auth/approle/role/sl

#Get the RoleID for "sl" role
ROLE=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
	localhost:8223/v1/auth/approle/role/sl/role-id | jq -r ".data[\"role_id\"]")

#Get the SecretID for "sl" role (automatically generated by Vault)
SECRET=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
	--request POST \
	localhost:8223/v1/auth/approle/role/sl/secret-id | jq -r ".data[\"secret_id\"]")
	
#echo "[HashiCorp Vault][AppRole authentication] RoleID for \"sl\" role: ${ROLE}"
#echo "[HashiCorp Vault][AppRole authentication] SecretID for \"sl\" role: ${SECRET}"

#Update environment variables of the Admin Server
sed -i "s/ROLE_ID=.*/ROLE_ID=\"${ROLE}\"/" apps/sl-auth/.env
sed -i "s/ROLE_SECRET=.*/ROLE_SECRET=\"${SECRET}\"/" apps/sl-auth/.env
